# Generated by Django 2.2.6 on 2019-12-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tollapp', '0002_auto_20191207_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='Mode_of_payment',
            field=models.CharField(choices=[('Paypal', 'Paypal'), ('Skrill', 'Skrill'), ('Neteller', 'Neteller'), ('PerfectMoney', 'Perfect Money'), ('Bitcoin', 'Bitcoin'), ('Luno', 'Luno'), ('Bitpay', 'Bitpay')], max_length=100, null=True),
        ),
    ]
